spring:
  datasource:
    url: jdbc:mysql://localhost:3306/be-hera?sessionVariables=sql_mode='NO_ENGINE_SUBSTITUTION'&jdbcCompliantTruncation=false
    username: root
    password: 123
  jpa:
    database-platform: org.springframework.orm.jpa.vendor.Database.MYSQL
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        type:
          preferred_instant_jdbc_type: TIMESTAMP
        globally_quoted_identifiers: false
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

openweather:
  api:
    key: 4d2df66bcae763e673d5a52bc949e9bc
